export {
  Bars3Icon,
  ChevronDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowPathIcon,
  Cog6ToothIcon,
  ChartBarIcon,
  ChatBubbleLeftRightIcon,
  PuzzlePieceIcon,
  SparklesIcon,
  RocketLaunchIcon,
  InformationCircleIcon,
  TrashIcon,
  ArrowDownTrayIcon,
  ArrowRightOnRectangleIcon,
  EyeIcon,
  EyeSlashIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  BoltIcon,
  HomeIcon,
  ShieldCheckIcon,
  CpuChipIcon,
  ArrowTrendingUpIcon,
  CursorArrowRaysIcon,
  Squares2X2Icon,
} from '@heroicons/vue/24/outline'
